-- MySQL Script generated by MySQL Workbench
-- Tuesday 27 August 2019 06:37:31 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Restaurant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `restarunt_id` INT NOT NULL,
  `resturant_name` VARCHAR(45) NULL,
  `restauranr_addr.` VARCHAR(45) NULL,
  PRIMARY KEY (`restarunt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `Customer_mob.` VARCHAR(45) NULL,
  `customer_add.` VARCHAR(45) NULL,
  `Restaurant_restarunt_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `Restaurant_restarunt_id`),
  INDEX `fk_Customer_Restaurant_idx` (`Restaurant_restarunt_id` ASC),
  CONSTRAINT `fk_Customer_Restaurant`
    FOREIGN KEY (`Restaurant_restarunt_id`)
    REFERENCES `mydb`.`Restaurant` (`restarunt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Items` (
  `item_id` INT NOT NULL,
  `item_name` VARCHAR(45) NULL,
  `item_price` VARCHAR(45) NULL,
  `item_addon` VARCHAR(45) NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deliveryboy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Deliveryboy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Deliveryboy` (
  `deliveryboy_id` INT NOT NULL,
  `deliveryboy_name` VARCHAR(45) NULL,
  `deliveryboy_mob.` VARCHAR(45) NULL,
  PRIMARY KEY (`deliveryboy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `order_id` INT NOT NULL,
  `Restaurant_restarunt_id` INT NOT NULL,
  `Deliveryboy_deliveryboy_id` INT NOT NULL,
  `Customer_customer_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `Deliveryboy_deliveryboy_id`, `Customer_customer_id`),
  INDEX `fk_Order_Restaurant1_idx` (`Restaurant_restarunt_id` ASC),
  INDEX `fk_Order_Deliveryboy1_idx` (`Deliveryboy_deliveryboy_id` ASC),
  INDEX `fk_Order_Customer1_idx` (`Customer_customer_id` ASC),
  CONSTRAINT `fk_Order_Restaurant1`
    FOREIGN KEY (`Restaurant_restarunt_id`)
    REFERENCES `mydb`.`Restaurant` (`restarunt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Deliveryboy1`
    FOREIGN KEY (`Deliveryboy_deliveryboy_id`)
    REFERENCES `mydb`.`Deliveryboy` (`deliveryboy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurant_has_Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Restaurant_has_Items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant_has_Items` (
  `Restaurant_restarunt_id` INT NOT NULL,
  `Items_item_id` INT NOT NULL,
  PRIMARY KEY (`Restaurant_restarunt_id`, `Items_item_id`),
  INDEX `fk_Restaurant_has_Items_Items1_idx` (`Items_item_id` ASC),
  INDEX `fk_Restaurant_has_Items_Restaurant1_idx` (`Restaurant_restarunt_id` ASC),
  CONSTRAINT `fk_Restaurant_has_Items_Restaurant1`
    FOREIGN KEY (`Restaurant_restarunt_id`)
    REFERENCES `mydb`.`Restaurant` (`restarunt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Restaurant_has_Items_Items1`
    FOREIGN KEY (`Items_item_id`)
    REFERENCES `mydb`.`Items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order_has_Items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Items` (
  `Order_order_id` INT NOT NULL,
  `Items_item_id` INT NOT NULL,
  `quantity` VARCHAR(45) NULL,
  `discount` VARCHAR(45) NULL,
  `add-on` VARCHAR(45) NULL,
  PRIMARY KEY (`Order_order_id`, `Items_item_id`),
  INDEX `fk_Order_has_Items_Items1_idx` (`Items_item_id` ASC),
  INDEX `fk_Order_has_Items_Order1_idx` (`Order_order_id` ASC),
  CONSTRAINT `fk_Order_has_Items_Order1`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `mydb`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Items_Items1`
    FOREIGN KEY (`Items_item_id`)
    REFERENCES `mydb`.`Items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
