-- MySQL Script generated by MySQL Workbench
-- Tuesday 27 August 2019 05:52:16 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Train` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Train` (
  `Train_no.` INT NOT NULL,
  `Train_name` VARCHAR(45) NULL,
  `Train_S` VARCHAR(45) NULL,
  `Train_END` VARCHAR(45) NULL,
  `Train_Shedule` VARCHAR(45) NULL,
  PRIMARY KEY (`Train_no.`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `age_Customer` VARCHAR(45) NULL,
  `gender_Customer` VARCHAR(45) NULL,
  `address` VARCHAR(70) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `PNR_Ticket` INT NOT NULL,
  `CustomerName_Ticket` VARCHAR(45) NULL,
  `R_U_Ticket` VARCHAR(45) NULL,
  `From_Ticket` VARCHAR(45) NULL,
  `To_Ticket` VARCHAR(45) NULL,
  `DoJ_Ticket` VARCHAR(45) NULL,
  `Gender_Ticket` VARCHAR(45) NULL,
  `Quota_Ticket` VARCHAR(45) NULL,
  `Price_Ticket` VARCHAR(45) NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Ticket_PNR_Ticket` INT NOT NULL,
  `Customer_idCustomer1` INT NOT NULL,
  PRIMARY KEY (`PNR_Ticket`, `Ticket_PNR_Ticket`, `Customer_idCustomer1`),
  INDEX `fk_Ticket_Customer1_idx` (`Customer_idCustomer1` ASC),
  CONSTRAINT `fk_Ticket_Customer1`
    FOREIGN KEY (`Customer_idCustomer1`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unreserved_Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Unreserved_Ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Unreserved_Ticket` (
  `PNR_Ticket` INT NOT NULL,
  `waiting_list` INT NOT NULL,
  PRIMARY KEY (`PNR_Ticket`),
  CONSTRAINT `fk_Unreserved_Ticket_1`
    FOREIGN KEY (`PNR_Ticket`)
    REFERENCES `mydb`.`Ticket` (`PNR_Ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserved_Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserved_Ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserved_Ticket` (
  `Train_Train_no.` INT NOT NULL,
  `Ticket_PNR_Ticket` INT NOT NULL,
  `seat_no.` VARCHAR(45) NULL,
  `coach_no.` VARCHAR(45) NULL,
  PRIMARY KEY (`Train_Train_no.`, `Ticket_PNR_Ticket`),
  INDEX `fk_Train_has_Ticket_Ticket1_idx` (`Ticket_PNR_Ticket` ASC),
  INDEX `fk_Train_has_Ticket_Train1_idx` (`Train_Train_no.` ASC),
  CONSTRAINT `fk_Train_has_Ticket_Train1`
    FOREIGN KEY (`Train_Train_no.`)
    REFERENCES `mydb`.`Train` (`Train_no.`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Train_has_Ticket_Ticket1`
    FOREIGN KEY (`Ticket_PNR_Ticket`)
    REFERENCES `mydb`.`Ticket` (`PNR_Ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
